import Link from "next/link";
import { ArrowUpRight, MapPin } from "lucide-react";
import { SitePage } from "@/components/site/SitePage";
import { getFeaturedStories } from "@/lib/stories";
import { getPublicProgrammes } from "@/lib/public-programmes";

export const dynamic = "force-dynamic";
export const metadata = { title: "Our work, StrayPaw", description: "Public case stories, completed programmes and field evidence intentionally published by StrayPaw partners." };

export default async function WorkPage() {
  const [stories, programmes] = await Promise.all([getFeaturedStories(12), getPublicProgrammes(12)]);
  return <SitePage kicker="StrayPaw field record" title={<>Work we can<br /><em>show you.</em></>} lede="This is StrayPaw's first-party evidence: resolved cases, dog stories and completed programmes that a partner has intentionally published. Operational notes, contacts and unresolved records remain with the field team." actions={<Link href="/evidence" className="product-primary">National evidence <ArrowUpRight size={16} /></Link>}><div className="grid gap-10 py-8 lg:grid-cols-2"><section><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.13em] text-paw-600">Case & dog stories</p><h2 className="text-2xl font-semibold tracking-tight text-bark-900 dark:text-bark-50">Real outcomes, in sequence.</h2><div className="mt-5 space-y-3">{stories.length ? stories.map((story) => <article key={story.id} className="border-b border-black/[.1] pb-4"><h3 className="font-semibold text-bark-900 dark:text-bark-50">{story.title}</h3><p className="mt-1 text-[13px] leading-relaxed text-bark-600 dark:text-bark-300">{story.public_summary}</p>{story.location_label && <span className="mt-2 inline-flex items-center gap-1 text-[12px] text-bark-500"><MapPin size={13} />{story.location_label}</span>}</article>) : <p className="text-[13px] text-bark-500">The first approved story will appear here.</p>}</div></section><section><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.13em] text-paw-600">Completed programmes</p><h2 className="text-2xl font-semibold tracking-tight text-bark-900 dark:text-bark-50">Aggregate work, not inflated claims.</h2><div className="mt-5 space-y-3">{programmes.length ? programmes.map((programme) => <article key={programme.id} className="border-b border-black/[.1] pb-4"><p className="text-[11px] font-semibold uppercase tracking-wide text-bark-500">{programme.ngo_name}</p><h3 className="mt-1 font-semibold text-bark-900 dark:text-bark-50">{programme.name}</h3>{programme.public_summary && <p className="mt-1 text-[13px] leading-relaxed text-bark-600 dark:text-bark-300">{programme.public_summary}</p>}<p className="mt-2 text-[12px] text-bark-500">{programme.animals_recorded.toLocaleString()} records documented{programme.sterilised_recorded ? ` · ${programme.sterilised_recorded.toLocaleString()} sterilised` : ""}</p></article>) : <p className="text-[13px] text-bark-500">Completed programmes appear after a partner verifies the aggregate and chooses to publish it.</p>}</div></section></div></SitePage>;
}
