"use client";

import { useMemo,useState } from "react";
import Link from "next/link";
import { ArrowUpRight,Crosshair,MapPin,Plus } from "lucide-react";
import { FieldMapPreview } from "@/components/site/FieldMapPreview";
import { DogPhoto } from "@/components/ui/DogPhoto";
import { located } from "@/lib/geo/cluster";
import { markerMetaFor } from "@/lib/marker-state";
import type { PublicCaseStory } from "@/lib/community-case-stories";
import { rescueCategory } from "@/lib/rescue-taxonomy";
import { dogLabel,timeAgo } from "@/lib/utils";
import type { Dog,Sighting } from "@/lib/types";

const RADIUS_KM=12;
function distanceKm(a:{lat:number;lng:number},b:{lat:number;lng:number}){const r=(v:number)=>v*Math.PI/180,e=6371,dLat=r(b.lat-a.lat),dLng=r(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLng/2)**2;return e*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function tone(d:Dog){if(d.needs_help)return "urgent" as const;return ["resolved","released","adopted","safe"].includes(String(d.status??"").toLowerCase())?"resolved" as const:"active" as const}

export function CommunityHome({dogs,sightings:_sightings,stories}:{dogs:Dog[];sightings:Sighting[];stories:PublicCaseStory[]}){
 const [location,setLocation]=useState<{lat:number;lng:number}|null>(null),[locating,setLocating]=useState(false),[error,setError]=useState<string|null>(null);
 const inView=useMemo(()=>{const rows=located(dogs);return location?rows.filter(d=>distanceKm(location,d)<=RADIUS_KM):rows},[dogs,location]);
 const register=useMemo(()=>[...inView].sort((a,b)=>Number(b.needs_help)-Number(a.needs_help)||+new Date(b.last_seen)-+new Date(a.last_seen)),[inView]);
 const scope=location?inView:dogs,needsHelp=scope.filter(d=>d.needs_help).length;
 const recent=useMemo(()=>{const seen=new Set<string>(),out:PublicCaseStory[]=[];for(const s of stories){if(!s.dog_id||seen.has(s.dog_id))continue;seen.add(s.dog_id);out.push(s);if(out.length===3)break}return out},[stories]);
 function findMe(){if(!navigator.geolocation){setError("Location is not available in this browser.");return}setLocating(true);navigator.geolocation.getCurrentPosition(({coords})=>{setLocation({lat:coords.latitude,lng:coords.longitude});setLocating(false);setError(null)},()=>{setError("We could not get your location. You can still explore the shared map.");setLocating(false)},{timeout:10000,maximumAge:300000})}
 return <main className="min-h-screen bg-[#f4f1e9] text-[#0b1e3d]"><div className="mx-auto max-w-7xl px-4 pb-16 pt-7 sm:px-6 lg:px-8">
  <header className="flex flex-col gap-6 border-b border-[#0b1e3d]/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#2457ce]">Community record</p><h1 className="mt-2 max-w-3xl text-[clamp(2.5rem,6vw,4.8rem)] font-semibold leading-[.91] tracking-[-.065em]">See who is here.<br/><span className="opacity-40">See what happened.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 opacity-55">Report a street animal, find one on the map, and follow its rescue through care and outcome.</p></div><Link href="/report" className="inline-flex h-11 items-center gap-2 self-start rounded-full bg-[#f05b40] px-5 text-sm font-semibold text-white sm:self-auto"><Plus size={16}/>Report an animal</Link></header>
  {error&&<p className="mt-3 text-xs text-[#b84734]">{error}</p>}

  <section className="mt-7 overflow-hidden border-y border-[#0b1e3d]/10 bg-white lg:grid lg:grid-cols-[1.65fr_.75fr]">
   <div className="relative min-h-[430px] lg:min-h-[590px]"><FieldMapPreview dogs={inView} center={location} place={location?"Around you":"Across India"}/><button onClick={findMe} disabled={locating} className="absolute left-4 top-4 z-10 inline-flex h-9 items-center gap-2 rounded-full bg-white/95 px-3 text-xs font-semibold shadow-sm backdrop-blur"><Crosshair size={13}/>{locating?"Finding you":location?"Around you":"Use my location"}</button>{!inView.length&&<div className="absolute inset-x-4 bottom-4 flex items-center justify-between gap-3 bg-white p-4 text-sm shadow-sm"><span><b>No animal recorded here yet.</b><span className="ml-2 opacity-55">A photo and location are enough.</span></span><Link href="/report" className="font-semibold">Report <ArrowUpRight className="inline" size={14}/></Link></div>}</div>
   <aside className="flex min-h-[430px] flex-col border-t border-[#0b1e3d]/10 p-5 lg:min-h-0 lg:border-l lg:border-t-0 lg:p-6"><div className="flex items-end justify-between border-b border-[#0b1e3d]/10 pb-4"><div><p className="text-[11px] font-bold uppercase tracking-[.13em] opacity-35">Nearby record</p><p className="mt-1 text-sm"><b className="text-xl">{scope.length}</b> <span className="opacity-45">animals</span>{needsHelp>0&&<><span className="mx-2 opacity-20">·</span><b className="text-[#f05b40]">{needsHelp}</b> <span className="opacity-45">need help</span></>}</p></div><Link href="/map" className="text-xs font-semibold text-[#2457ce]">Full map</Link></div><div className="divide-y divide-[#0b1e3d]/8">{register.slice(0,6).map(d=>{const m=markerMetaFor(d);return <Link href={`/dog/${d.id}`} key={d.id} className="grid grid-cols-[48px_1fr_auto] items-center gap-3 py-3"><DogPhoto src={d.cover_photo} alt="" seed={d.id} tone={tone(d)} className="h-12 w-12 rounded-lg object-cover"/><span className="min-w-0"><b className="block truncate text-sm">{dogLabel(d)}</b><small className="block truncate text-xs opacity-45">{d.zone||"Location recorded"}</small></span><span className="text-right"><small className="block text-[10px] font-semibold" style={{color:m.color}}>{m.label}</small><small className="mt-1 block text-[10px] opacity-35">{timeAgo(d.last_seen)}</small></span></Link>})}</div><Link href="/map" className="mt-auto inline-flex items-center gap-1 pt-5 text-xs font-semibold">Find an animal <ArrowUpRight size={13}/></Link></aside>
  </section>

  <section className="mt-10"><div className="flex items-end justify-between gap-4 border-b border-[#0b1e3d]/10 pb-4"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] opacity-35">Rescue stories</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.035em]">What happened next</h2></div><Link href="/stories" className="text-xs font-semibold text-[#2457ce]">All stories <ArrowUpRight className="inline" size={13}/></Link></div>{recent.length?<div className="grid md:grid-cols-3">{recent.map((s,i)=>{const done=true,name=s.animal_name||s.animal_code||"Animal record",category=rescueCategory({subtype:s.category,title:s.title,detail:s.outcome});return <Link key={s.dog_id} href={`/dog/${s.dog_id}`} className={`group py-6 md:px-6 ${i?"border-t border-[#0b1e3d]/10 md:border-l md:border-t-0":""} md:first:pl-0`}><DogPhoto src={s.cover_photo} alt={name} seed={s.dog_id} tone={done?"resolved":"active"} className="aspect-[16/9] w-full rounded-xl object-cover"/><div className="mt-4 flex items-start justify-between gap-4"><div><p className={`text-[10px] font-bold uppercase tracking-[.1em] ${done?"text-[#46755a]":"text-[#f05b40]"}`}>{done?"Journey completed":"In progress"}</p><h3 className="mt-1 text-lg font-semibold tracking-[-.025em]">{name}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 opacity-55">{s.title||category}</p></div><ArrowUpRight size={16} className="mt-1 shrink-0 opacity-20 transition group-hover:opacity-70"/></div></Link>})}</div>:<p className="py-8 text-sm opacity-50">Rescue stories appear here as field records connect to an animal.</p>}</section>

  <footer className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-[#0b1e3d]/10 pt-5 text-xs"><span className="opacity-45">Locations are approximate. Sensitive operational details stay private.</span><div className="flex gap-5 font-semibold"><Link href="/map">Map</Link><Link href="/stories">Stories</Link><Link href="/orgs">Organisations</Link></div></footer>
 </div></main>;
}
