import { NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase";

export const runtime="nodejs";
const htmlEsc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
const within=(value:unknown,from:number|null,to:number|null)=>{if(!from&&!to)return true;const t=Date.parse(String(value??""));return Number.isFinite(t)&&(!from||t>=from)&&(!to||t<=to)};
const contains=(value:unknown,q:string|null)=>!q||String(value??"").toLowerCase().includes(q.toLowerCase());

async function actor(request:Request){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");const admin=getSupabaseAdmin();if(!admin||!token)return null;const {data:user}=await admin.auth.getUser(token);if(!user.user)return null;const {data:member}=await admin.from("ngo_members").select("ngo_id").eq("user_id",user.user.id).maybeSingle();return member?.ngo_id?{admin,ngoId:member.ngo_id as string}:null}
async function paged(load:(a:number,b:number)=>any,max=25000){const rows:any[]=[];for(let a=0;a<max;a+=1000){const {data,error}=await load(a,Math.min(a+999,max-1));if(error)break;rows.push(...(data??[]));if(!data||data.length<1000)break}return rows}

export async function GET(request:Request){
 const current=await actor(request);if(!current)return NextResponse.json({error:"Organisation access required."},{status:401});
 const url=new URL(request.url),year=url.searchParams.get("year"),fromText=url.searchParams.get("from")||(year?`${year}-01-01`:null),toText=url.searchParams.get("to")||(year?`${year}-12-31`:null),from=fromText?Date.parse(`${fromText}T00:00:00`):null,to=toText?Date.parse(`${toText}T23:59:59.999`):null,locality=url.searchParams.get("locality")?.trim()||null,scopeType=url.searchParams.get("scopeType")??"all",scopeId=url.searchParams.get("scopeId")||null;
 const [{data:ngo},animals,cases,care]=await Promise.all([
  current.admin.from("ngos").select("id,name,logo_url,city,state").eq("id",current.ngoId).maybeSingle(),
  paged((a,b)=>current.admin.from("dogs").select("id,name,code,straypaw_id,species,zone,cover_photo,campaign_id").eq("ngo_id",current.ngoId).order("last_seen",{ascending:false}).range(a,b)),
  paged((a,b)=>current.admin.from("cases").select("id,dog_id,title,category,status,outcome_note,resolution,source_event_at,created_at,resolved_at,zone,dogs(campaign_id)").eq("ngo_id",current.ngoId).order("last_activity_at",{ascending:false}).range(a,b)),
  paged((a,b)=>current.admin.from("medical_events").select("id,dog_id,kind,event_date,notes,dogs!inner(campaign_id,ngo_id)").eq("dogs.ngo_id",current.ngoId).order("event_date",{ascending:false}).range(a,b)),
 ]);
 let scope="Organisation-wide animal stories";if(scopeType==="campaign"&&scopeId){const {data}=await current.admin.from("campaigns").select("name").eq("id",scopeId).eq("ngo_id",current.ngoId).maybeSingle();if(data)scope=data.name;}
 const campaignOk=(id:unknown)=>scopeType!=="campaign"||!scopeId||id===scopeId;
 const caseRows=cases.filter((r:any)=>within(r.source_event_at??r.created_at,from,to)&&campaignOk(r.dogs?.campaign_id)&&contains(r.zone,locality));
 const careRows=care.filter((r:any)=>within(r.event_date,from,to)&&campaignOk(r.dogs?.campaign_id));
 const byCase=new Map<string,any[]>(),byCare=new Map<string,any[]>();for(const r of caseRows)if(r.dog_id)byCase.set(r.dog_id,[...(byCase.get(r.dog_id)??[]),r]);for(const r of careRows)if(r.dog_id)byCare.set(r.dog_id,[...(byCare.get(r.dog_id)??[]),r]);
 const stories=animals.filter((a:any)=>campaignOk(a.campaign_id)&&contains(a.zone,locality)&&(byCase.has(a.id)||byCare.has(a.id))).map((a:any)=>{const cs=(byCase.get(a.id)??[]).sort((x,y)=>Date.parse(y.source_event_at??y.created_at??"")-Date.parse(x.source_event_at??x.created_at??"")),ms=(byCare.get(a.id)??[]).sort((x,y)=>Date.parse(y.event_date??"")-Date.parse(x.event_date??"")),outcome=cs.find((c:any)=>c.outcome_note||c.resolution)?.outcome_note??cs.find((c:any)=>c.resolution)?.resolution??"",latest=Math.max(Date.parse(cs[0]?.source_event_at??cs[0]?.created_at??"")||0,Date.parse(ms[0]?.event_date??"")||0);return{a,cs,ms,outcome,latest}}).sort((a:any,b:any)=>b.latest-a.latest).slice(0,36);
 const cards=stories.map(({a,cs,ms,outcome}:any)=>{const timeline=[...cs.slice(0,2).map((c:any)=>({date:c.source_event_at??c.created_at,title:c.title||c.category||"Case"})),...ms.slice(0,3).map((m:any)=>({date:m.event_date,title:String(m.kind||"Care").replace(/_/g," ")}))].sort((x,y)=>Date.parse(y.date)-Date.parse(x.date)).slice(0,4);return `<article class="card">${a.cover_photo?`<img src="${htmlEsc(a.cover_photo)}" alt="${htmlEsc(a.name||a.straypaw_id||"Animal")}">`:`<div class="photo-fallback">${htmlEsc(String(a.species||"animal").toUpperCase())}</div>`}<div class="body"><p class="id">${htmlEsc(a.straypaw_id||a.id)}${a.code?` <span>Source ${htmlEsc(a.code)}</span>`:""}</p><h2>${htmlEsc(a.name||`${a.species||"Animal"} near ${a.zone||"recorded area"}`)}</h2><p class="meta">${htmlEsc([a.species,a.zone].filter(Boolean).join(" · "))}</p><div class="numbers"><b>${cs.length}<small>cases</small></b><b>${ms.length}<small>care events</small></b></div>${outcome?`<p class="outcome"><strong>Outcome</strong> ${htmlEsc(String(outcome).replace(/_/g," "))}</p>`:""}<div class="timeline">${timeline.map((e:any)=>`<p><time>${htmlEsc(String(e.date||"").slice(0,10))}</time>${htmlEsc(e.title)}</p>`).join("")}</div></div></article>`}).join("");
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>${htmlEsc(ngo?.name??"Organisation")} animal story pack</title><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;background:#f4f1eb;color:#0b1e3d;font-family:Arial,sans-serif}.page{max-width:1100px;margin:auto;padding:32px}.head{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;border-bottom:3px solid #2457ce;padding-bottom:18px}.kicker{font-size:11px;font-weight:800;letter-spacing:.14em;color:#2457ce}.head h1{font-size:34px;margin:6px 0}.muted{font-size:12px;color:#667085}.brand{font-weight:900}.brand i{color:#f05b40;font-style:normal}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:24px}.card{break-inside:avoid;background:white;border:1px solid #dde1e8;border-radius:14px;overflow:hidden}.card img,.photo-fallback{width:100%;height:210px;object-fit:cover}.photo-fallback{display:grid;place-items:center;background:#e9edf5;font-weight:900;letter-spacing:.16em;color:#50617d}.body{padding:16px}.id{font-size:10px;font-weight:800;letter-spacing:.08em;color:#2457ce}.id span{color:#7a8495;margin-left:8px}.body h2{font-size:22px;margin:5px 0}.meta{font-size:12px;color:#667085}.numbers{display:flex;gap:24px;border-block:1px solid #edf0f4;margin:14px 0;padding:10px 0}.numbers b{font-size:22px}.numbers small{display:block;font-size:9px;text-transform:uppercase;color:#7a8495}.outcome{font-size:12px;background:#f3f6fb;padding:9px;border-radius:8px}.timeline p{display:grid;grid-template-columns:88px 1fr;gap:8px;font-size:11px;border-top:1px solid #eee;padding:7px 0;margin:0}.timeline time{color:#7a8495}.print{position:fixed;right:18px;top:18px;background:#0b1e3d;color:#fff;border:0;border-radius:8px;padding:10px 14px;font-weight:700}@media print{body{background:white}.page{padding:0}.print{display:none}.grid{gap:10px}.card img,.photo-fallback{height:150px}}@media(max-width:720px){.grid{grid-template-columns:1fr}.head{align-items:flex-start;flex-direction:column}}</style></head><body><button class="print" onclick="window.print()">Print / Save PDF</button><main class="page"><header class="head"><div><div class="kicker">ANIMAL EVIDENCE STORIES</div><h1>${htmlEsc(scope)}</h1><p class="muted">${htmlEsc(ngo?.name??"Organisation")} · ${htmlEsc([ngo?.city,ngo?.state].filter(Boolean).join(", "))} · ${htmlEsc(fromText||toText?`${fromText??"Start"} to ${toText??"Present"}`:"All time")}</p></div><div class="brand">StrayPaw<i>.</i></div></header>${stories.length?`<section class="grid">${cards}</section>`:`<p class="muted" style="margin-top:32px">No animal stories match this scope yet.</p>`}<p class="muted" style="margin-top:24px">Generated from traceable StrayPaw animal, case and care records. Private reporter contact details are excluded.</p></main></body></html>`;
 return new Response(html,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}});
}
