"use client";

import { useState } from "react";
import { Download, FileSpreadsheet, FileText, Loader2, Share2 } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

type Format = "xlsx" | "csv";
type ExportType = "report" | "cases" | "animals";
export function ExportStudio() {
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function download(type: ExportType, format: Format) { setBusy(`${type}-${format}`); setError(null); try { const supa = getSupabase(); const token = supa ? (await supa.auth.getSession()).data.session?.access_token : null; const res = await fetch(`/api/partner/export?type=${type}&format=${format}`, { headers: token ? { Authorization: `Bearer ${token}` } : undefined }); if (!res.ok) throw new Error(res.status === 401 ? "Verified partners only." : "Export failed."); const blob = await res.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `straypaw-${type}.${format}`; link.click(); URL.revokeObjectURL(link.href); } catch (e) { setError(e instanceof Error ? e.message : "Export failed."); } finally { setBusy(null); } }
  const Button = ({ type, format, children }: { type: ExportType; format: Format; children: React.ReactNode }) => <button onClick={() => void download(type, format)} disabled={!!busy} className="export-studio-action">{busy === `${type}-${format}` ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}{children}</button>;
  return <section className="export-studio" aria-labelledby="export-studio-title"><div className="export-studio-intro"><span className="product-kicker">Take the record with you</span><h2 id="export-studio-title">One record. Every audience.</h2><p>Export a clean operating file, a funder-ready evidence pack or a story brief without re-entering data. Private contacts and raw informer fields stay out of these exports.</p></div><div className="export-studio-grid"><article><FileSpreadsheet className="h-5 w-5" /><h3>Operations handoff</h3><p>Cases, animals and care history in a clean workbook for clinics, teams and backups.</p><div><Button type="report" format="xlsx">Full XLSX pack</Button><Button type="report" format="csv">CSV</Button></div></article><article><FileText className="h-5 w-5" /><h3>Funding & government</h3><p>Print this filtered analytics view as a polished PDF, then attach the underlying cases when a reviewer asks.</p><div><button onClick={() => window.print()} className="export-studio-action"><FileText className="h-4 w-4" />Save report as PDF</button><Button type="cases" format="xlsx">Underlying cases</Button></div></article><article><Share2 className="h-5 w-5" /><h3>Stories & reels</h3><p>Pull clean animal records and case outcomes to build approved social stories, impact carousels and reel scripts.</p><div><Button type="animals" format="xlsx">Animal story pack</Button><Button type="cases" format="csv">Outcome CSV</Button></div></article></div>{error && <p role="alert" className="mt-3 text-[12px] font-medium text-status-injured">{error}</p>}</section>;
}
