"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CalendarClock, MapPin, Search } from "lucide-react";
import { useAuth } from "@/components/auth/AuthProvider";
import { getMyAnimals } from "@/lib/animal-actions";
import { getPartnerRecordRows, type PartnerRecordRow } from "@/lib/partner-record-explorer";
import { isClosedStatus, isNoAction, rescueCategory } from "@/lib/rescue-taxonomy";

const followDone=(status:string|null)=>["done","completed","cancelled","canceled","missed"].includes(String(status??"").toLowerCase());
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;

export function PartnerRecordHome(){
 const {user,ready}=useAuth();
 const [rows,setRows]=useState<PartnerRecordRow[]|null>(null),[animals,setAnimals]=useState(0);
 useEffect(()=>{if(!ready||!user)return;Promise.all([getPartnerRecordRows(),getMyAnimals()]).then(([r,a])=>{setRows(r);setAnimals(a.length)}).catch(()=>{setRows([]);setAnimals(0)})},[ready,user?.id]);
 const s=useMemo(()=>{const all=rows??[],now=Date.now(),rescues=all.filter(r=>r.kind==="rescue"),outcomes=all.filter(r=>r.kind==="outcome"),followups=all.filter(r=>r.kind==="follow_up"),open=rescues.filter(r=>!isClosedStatus(r.status)),closed=rescues.filter(r=>isClosedStatus(r.status)),noAction=outcomes.filter(r=>isNoAction({title:r.title,detail:r.detail,subtype:r.subtype,status:r.status})),overdue=followups.filter(r=>!followDone(r.status)&&+new Date(r.date)<now),next7=followups.filter(r=>!followDone(r.status)&&+new Date(r.date)>=now&&+new Date(r.date)<=now+604800000);const cats=new Map<string,number>(),places=new Map<string,{total:number;open:number;noAction:number}>(),byAnimal=new Map<string,number>();for(const r of rescues){const c=rescueCategory(r);cats.set(c,(cats.get(c)??0)+1);const k=r.locality||"Not recorded",v=places.get(k)??{total:0,open:0,noAction:0};v.total++;if(!isClosedStatus(r.status))v.open++;places.set(k,v);if(r.animalId)byAnimal.set(r.animalId,(byAnimal.get(r.animalId)??0)+1)}for(const r of noAction){const k=r.locality||"Not recorded",v=places.get(k)??{total:0,open:0,noAction:0};v.noAction++;places.set(k,v)}return{rescues,open,closed,noAction,overdue,next7,completion:pct(closed.length,rescues.length),repeat:[...byAnimal.values()].filter(n=>n>1).length,categories:[...cats.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5),places:[...places.entries()].map(([name,v])=>({name,...v,score:v.open*3+v.noAction*2+v.total*.15})).sort((a,b)=>b.score-a.score).slice(0,5)}},[rows]);
 if(rows===null)return <main className="mx-auto max-w-6xl px-5 py-10 text-sm opacity-50">Loading organisation record…</main>;
 const max=Math.max(1,...s.categories.map(([,n])=>n));
 return <main className="min-h-screen bg-[#f4f1e9] text-[#0b1e3d]"><div className="mx-auto max-w-7xl px-4 pb-16 pt-7 sm:px-6 lg:px-8">
  <header className="flex flex-col gap-5 border-b border-[#0b1e3d]/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#2457ce]">Today</p><h1 className="mt-2 text-[clamp(2.3rem,5vw,4rem)] font-semibold leading-[.95] tracking-[-.055em]">What needs attention.</h1><p className="mt-3 max-w-xl text-sm leading-6 opacity-55">One view of unfinished work. Records holds the detail; the map shows where the pressure is building.</p></div><Link href="/partner/records" className="inline-flex h-10 items-center gap-2 self-start rounded-full bg-[#0b1e3d] px-4 text-sm font-semibold text-white sm:self-auto"><Search size={14}/>Find a record</Link></header>

  {s.rescues.length===0&&animals===0&&<section className="grid gap-6 border-b border-[#0b1e3d]/10 py-8 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] opacity-35">Set up your workspace</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.035em]">Start with the records you already use.</h2><p className="mt-2 max-w-2xl text-sm leading-6 opacity-55">Import an existing workbook, open your first rescue case, or add an animal directly. StrayPaw keeps your source IDs while creating a permanent animal identity underneath.</p></div><div className="flex flex-wrap gap-3"><Link href="/partner/import" className="rounded-full bg-[#0b1e3d] px-4 py-2.5 text-sm font-semibold text-white">Import workbook</Link><Link href="/partner/cases/new" className="rounded-full border border-[#0b1e3d]/15 px-4 py-2.5 text-sm font-semibold">New rescue case</Link></div></section>}

  <section className="grid border-b border-[#0b1e3d]/10 md:grid-cols-3">
   <Signal href="/partner/records?view=rescue" value={s.open.length} label="Open rescues" note="Still in progress" hot={s.open.length>0}/>
   <Signal href="/partner/records?view=overdue" value={s.overdue.length} label="Follow-ups overdue" note={`${s.next7.length} due in the next 7 days`} hot={s.overdue.length>0}/>
   <Signal href="/partner/reports" value={s.noAction.length} label="No intervention" note="Closed without field action" hot={s.noAction.length>0}/>
  </section>

  <div className="grid border-b border-[#0b1e3d]/10 lg:grid-cols-[1.05fr_.95fr]">
   <section className="py-8 lg:border-r lg:border-[#0b1e3d]/10 lg:pr-10"><div className="flex items-baseline justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] opacity-40">Incoming work</p><h2 className="mt-1 text-xl font-semibold tracking-[-.025em]">What keeps happening</h2></div><Link href="/partner/reports" className="text-xs font-semibold text-[#2457ce]">Analyse <ArrowUpRight className="inline" size={13}/></Link></div><div className="mt-7 space-y-5">{s.categories.map(([name,n],i)=><div key={name} className="grid grid-cols-[1fr_auto] items-end gap-4"><div><div className="mb-2 flex items-baseline justify-between gap-4"><span className="text-sm font-medium capitalize">{name}</span><span className="text-xs tabular-nums opacity-45">{n.toLocaleString()}</span></div><div className="h-[3px] bg-[#0b1e3d]/8"><div className={`h-full ${i===0?"bg-[#f05b40]":"bg-[#2457ce]"}`} style={{width:`${Math.max(3,n/max*100)}%`}}/></div></div></div>)}</div></section>
   <section className="py-8 lg:pl-10"><div className="flex items-baseline justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] opacity-40">Field pressure</p><h2 className="mt-1 text-xl font-semibold tracking-[-.025em]">Where to act next</h2></div><Link href="/partner/map" className="inline-flex items-center gap-1 text-xs font-semibold text-[#2457ce]">Map <MapPin size={12}/></Link></div><div className="mt-5 divide-y divide-[#0b1e3d]/8">{s.places.map((p,i)=><Link href="/partner/map" key={p.name} className="grid grid-cols-[28px_1fr_auto] items-center gap-3 py-3.5"><span className="text-xs tabular-nums opacity-30">0{i+1}</span><span className="min-w-0"><b className="block truncate text-sm capitalize">{p.name}</b><small className="text-xs opacity-45">{p.open} open · {p.noAction} no action</small></span><span className="text-sm font-semibold tabular-nums">{p.total}</span></Link>)}</div></section>
  </div>

  <footer className="grid gap-5 py-7 sm:grid-cols-[1fr_auto] sm:items-center"><div className="flex flex-wrap gap-x-8 gap-y-3 text-sm"><Metric value={`${s.completion}%`} label="cases completed"/><Metric value={s.repeat.toLocaleString()} label="repeat animals"/><Metric value={animals.toLocaleString()} label="animals on record"/></div><div className="flex gap-5 text-sm font-semibold"><Link href="/partner/map">Map</Link><Link href="/partner/reports">Reports</Link><Link href="/partner/records">Records</Link></div></footer>
 </div></main>;
}
function Signal({href,value,label,note,hot}:{href:string;value:number;label:string;note:string;hot:boolean}){return <Link href={href} className="group py-7 md:border-r md:border-[#0b1e3d]/10 md:px-7 md:first:pl-0 md:last:border-r-0"><div className="flex items-start justify-between"><strong className={`text-5xl font-semibold tracking-[-.06em] tabular-nums ${hot?"text-[#f05b40]":""}`}>{value.toLocaleString()}</strong><ArrowUpRight size={16} className="mt-1 opacity-20 transition group-hover:opacity-70"/></div><p className="mt-3 text-sm font-semibold">{label}</p><p className="mt-1 text-xs opacity-45">{note}</p></Link>}
function Metric({value,label}:{value:string;label:string}){return <span><b className="tabular-nums">{value}</b> <span className="opacity-45">{label}</span></span>}
