"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Download, Loader2, Plus } from "lucide-react";
import { getSurveys, getSurveyResponses, type } from "@/lib/surveys";
import { createSurvey, submitSurveyResponse } from "@/lib/survey-actions";

const MARKER="STRAYPAW_PROJECT_FIELDS:";
type Project={id:string;title:string;species:string;description:string|null;status:string;created_at:string};
type ResponseRow={id:string;attributes:Record<string,unknown>;notes:string|null;created_at:string;count:number;species:string|null};
function fieldsOf(p:Project){const line=(p.description??"").split("\n").find(x=>x.startsWith(MARKER));return line?line.slice(MARKER.length).split("|").map(x=>x.trim()).filter(Boolean):[]}
function humanDescription(p:Project){return (p.description??"").split("\n").filter(x=>!x.startsWith(MARKER)).join("\n").trim()}

export function ProjectRegisters(){
 const [projects,setProjects]=useState<Project[]|null>(null),[selected,setSelected]=useState<string>(""),[responses,setResponses]=useState<ResponseRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const [name,setName]=useState(""),[species,setSpecies]=useState("dog"),[fieldText,setFieldText]=useState(""),[description,setDescription]=useState("");
 const [values,setValues]=useState<Record<string,string>>({}),[notes,setNotes]=useState("");
 async function reload(){const all=(await getSurveys()) as unknown as Project[];const p=all.filter(x=>(x.description??"").includes(MARKER));setProjects(p);setSelected(s=>s||p[0]?.id||"")}
 useEffect(()=>{reload().catch(()=>setProjects([]))},[]);
 useEffect(()=>{if(!selected){setResponses([]);return}getSurveyResponses(selected,1000).then(r=>setResponses(r as unknown as ResponseRow[])).catch(()=>setResponses([]))},[selected]);
 const project=projects?.find(p=>p.id===selected)||null,fields=project?fieldsOf(project):[];
 async function makeProject(e:FormEvent){e.preventDefault();const f=fieldText.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);if(!name.trim()||!f.length)return;setBusy(true);setError(null);try{const id=await createSurvey(name.trim(),species,`${MARKER}${f.join("|")}\n${description.trim()}`);await reload();if(id)setSelected(id);setName("");setFieldText("");setDescription("")}catch(e){setError(e instanceof Error?e.message:"Could not create project") }finally{setBusy(false)}}
 async function addEntry(e:FormEvent){e.preventDefault();if(!project)return;setBusy(true);setError(null);try{await submitSurveyResponse({surveyId:project.id,species:project.species,count:1,attributes:Object.fromEntries(fields.map(f=>[f,values[f]||""])),notes:notes||null});setValues({});setNotes("");setResponses(await getSurveyResponses(project.id,1000) as unknown as ResponseRow[])}catch(e){setError(e instanceof Error?e.message:"Could not save entry")}finally{setBusy(false)}}
 function exportCsv(){if(!project)return;const cols=["created_at",...fields,"notes"];const esc=(v:unknown)=>{const s=String(v??"");return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};const csv=[cols.join(","),...responses.map(r=>[r.created_at,...fields.map(f=>r.attributes?.[f]),r.notes].map(esc).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=`${project.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-register.csv`;a.click();URL.revokeObjectURL(url)}
 if(projects===null)return <div className="flex justify-center py-20"><Loader2 className="h-5 w-5 animate-spin"/></div>;
 return <div><header className="mb-6"><span className="product-kicker">Flexible fieldwork</span><h1 className="mt-1 text-2xl font-semibold">Project registers</h1><p className="mt-2 max-w-2xl text-sm opacity-70">Create the columns a project actually needs. Rabies, equine hoof care, education questionnaires, treatment camps and future workflows can all use the same register without changing StrayPaw’s core animal record.</p></header>
 <form onSubmit={makeProject} className="grid gap-3 border-y border-black/[.08] py-5 sm:grid-cols-2"><label className="text-xs font-semibold">Project name<input className="mt-1 h-10 w-full border border-black/[.1] bg-white px-3 text-sm font-normal" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Horse hoof-care project"/></label><label className="text-xs font-semibold">Species<input className="mt-1 h-10 w-full border border-black/[.1] bg-white px-3 text-sm font-normal" value={species} onChange={e=>setSpecies(e.target.value)} placeholder="horse, dog, cattle…"/></label><label className="text-xs font-semibold sm:col-span-2">Fields<textarea className="mt-1 min-h-20 w-full border border-black/[.1] bg-white p-3 text-sm font-normal" value={fieldText} onChange={e=>setFieldText(e.target.value)} placeholder="Hoof condition, shoe replaced, treatment, next review"/></label><label className="text-xs font-semibold sm:col-span-2">Purpose / notes<input className="mt-1 h-10 w-full border border-black/[.1] bg-white px-3 text-sm font-normal" value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy} className="inline-flex h-10 items-center justify-center gap-2 bg-[#0b1e3d] px-4 text-sm font-semibold text-white sm:w-fit"><Plus size={15}/>Create register</button></form>
 {error&&<p className="mt-3 text-sm text-red-700">{error}</p>}
 {projects.length>0&&<div className="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="border-t border-black/[.1]">{projects.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={`w-full border-b border-black/[.08] px-2 py-3 text-left text-sm ${selected===p.id?"font-semibold text-[#2457ce]":""}`}><span className="block">{p.title}</span><small className="opacity-55">{fieldsOf(p).length} fields</small></button>)}</aside>{project&&<section><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">{project.title}</h2>{humanDescription(project)&&<p className="mt-1 text-sm opacity-65">{humanDescription(project)}</p>}</div><button type="button" onClick={exportCsv} className="inline-flex items-center gap-2 text-sm font-semibold"><Download size={14}/>Export</button></div><form onSubmit={addEntry} className="mt-4 grid gap-3 border-y border-black/[.08] py-4 sm:grid-cols-2">{fields.map(f=><label key={f} className="text-xs font-semibold">{f}<input value={values[f]||""} onChange={e=>setValues(v=>({...v,[f]:e.target.value}))} className="mt-1 h-10 w-full border border-black/[.1] bg-white px-3 text-sm font-normal"/></label>)}<label className="text-xs font-semibold sm:col-span-2">Notes<input value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 h-10 w-full border border-black/[.1] bg-white px-3 text-sm font-normal"/></label><button disabled={busy} className="h-10 bg-[#2457ce] px-4 text-sm font-semibold text-white sm:w-fit">Add entry</button></form><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] border-collapse text-left text-sm"><thead><tr className="border-b border-black/[.1] text-xs opacity-55"><th className="py-3">Date</th>{fields.map(f=><th key={f}>{f}</th>)}<th>Notes</th></tr></thead><tbody>{responses.map(r=><tr key={r.id} className="border-b border-black/[.07]"><td className="py-3 pr-4 text-xs">{new Date(r.created_at).toLocaleDateString()}</td>{fields.map(f=><td key={f} className="pr-4">{String(r.attributes?.[f]??"—")}</td>)}<td className="text-xs opacity-65">{r.notes||"—"}</td></tr>)}</tbody></table>{!responses.length&&<p className="py-6 text-sm opacity-55">No entries yet.</p>}</div></section>}</div>}
 </div>;
}
